config/routes.rb
Rails.application.routes.draw do

  resources :portfolio
  get 'portfolio/index'
  get 'portfolio/new'
  get 'portfolio/show'
  get 'portfolio/edit'
  get 'portfolio/delete'

  resources :apply
  get 'apply/index'

  resources :applications
  get 'applications/index'
  get 'applications/new'
  get 'applications/show'
  get 'applications/edit'
  get 'applications/drop'

  resources :posts
  get 'posts/show'
  get 'posts/new'
  get 'posts/edit'
  get 'posts/delete'

  resources :feed
  get 'feed/index'
  get 'feed/show'

  resources :categories
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'categories/edit'
  get 'categories/delete'
  get 'welcome/index'

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end

  def drop
  end
end

app/controllers/apply_controller.rb
class ApplyController < ApplicationController
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to(:action => 'show', :id => @category.id)
    else
      render('index')
    end
  end

  def delete
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id]).destroy
    redirect_to(:action => 'index')
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/feed_controller.rb
# feed controller only shows posts

class FeedController < ApplicationController
  def index
    @posts = Post.all
    @categories = Category.all
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end

  def delete
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to(:action => 'show', :id => @post.id)
    else
      render('new')
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find([params[:id]])
    if @post.update_attributes(post_params)
      redirect_to(:action => 'show', :id => @post.id)
    else
      render('')
    end
  end

  def delete
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    redirect_to(:action => '')
  end


  private
  def post_params
    params.require(:post).permit(:title, :description, :category)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/drop.html.erb
<h1>Applications#drop</h1>
<p>Find me in app/views/applications/drop.html.erb</p>

app/views/applications/edit.html.erb
<h1>Applications#edit</h1>
<p>Find me in app/views/applications/edit.html.erb</p>

app/views/applications/index.html.erb
<!-- your applications -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/feed">lightbulb</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/posts/new"><span class="glyphicon glyphicon-plus"></span> New Project</a></li>
        <li><a href="/posts">Your Projects</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">John Doe <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="/portfolio">
                <span class="glyphicon glyphicon-user"></span>
                <span class="dropdown-text"> Portfolio</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-file"></span>
                <span class="dropdown-text"> Applications</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-star"></span>
                <span class="dropdown-text"> Starred</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-list"></span>
                <span class="dropdown-text"> History</span>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-cog"></span>
                <span class="dropdown-text"> Settings</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-off"></span>
                <span class="dropdown-text"> Logout</span>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

app/views/applications/new.html.erb
<h1>Applications#new</h1>
<p>Find me in app/views/applications/new.html.erb</p>

app/views/applications/show.html.erb
<h1>Applications#show</h1>
<p>Find me in app/views/applications/show.html.erb</p>

app/views/apply/index.html.erb
<!-- apply page -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/feed">lightbulb</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/posts/new"><span class="glyphicon glyphicon-plus"></span> New Project</a></li>
        <li><a href="/posts">Your Projects</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">John Doe <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="/portfolio">
                <span class="glyphicon glyphicon-user"></span>
                <span class="dropdown-text"> Portfolio</span>
              </a>
            </li>
            <li>
              <a href="/applications">
                <span class="glyphicon glyphicon-file"></span>
                <span class="dropdown-text"> Applications</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-star"></span>
                <span class="dropdown-text"> Starred</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-list"></span>
                <span class="dropdown-text"> History</span>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-cog"></span>
                <span class="dropdown-text"> Settings</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-off"></span>
                <span class="dropdown-text"> Logout</span>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</nav>



<div class="container">
  <div class="row">
    <h1 class="page-header">Apply</h1>
  </div>
  <div class="row">
    <div class="col-md-8">
      <h3 class="">A Rad Music Project</h3>

      <div class="row">
        <div class="col-md-12">
          <div class="thumbnail">
            <%= image_tag("musicbar.png") %>
          </div>
        </div>
        <div class="col-md-12">
          <div class="thumbnail">
            <a href="#">
              <div class="caption">
                <span class="glyphicon glyphicon-plus"></span>
                <span class="">Add sample</span>
              </div>
            </a>
          </div>
        </div>
        <!--<div class="col-md-6">
          <div class="thumbnail">
            <a href="#">
              <div class="caption newpost-media">
                <span class="glyphicon glyphicon-plus"></span>
                <span class="">Add sample</span>
              </div>
            </a>
          </div>
        </div>-->
      </div>

      <h5>Provide your statement</h5>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <textarea name="comment" form="newpost" placeholder="" rows="6" class="form-control"></textarea>
          </div>
        </div>
        <div class="col-md-12">
          <p style="text-align: right"><a class="btn btn-success" href="#" role="button">Apply</a></p>
        </div>
      </div>

    </div>
    <div class="col-md-4">
      <h3 class="">Position Requirements</h3>
      <p>Nunc malesuada pretium consequat. Phasellus felis ligula, convallis sit amet augue at, tempor rutrum nibh.
        Sed sodales tristique magna ac dictum. Vestibulum non aliquet nibh. </p>
      <ul>
        <li>blah blah blah blah</li>
        <li>blae blae blae blae blae</li>
        <li>bl</li>
      </ul>

      <h3 class="">Project Description</h3>
      <p>Nulla eget mollis turpis. Donec euismod euismod magna, eu viverra felis rhoncus sit amet. Morbi
        finibus, orci efficitur tristique volutpat, elit dolor pellentesque mi, eu varius nunc tortor sed augue. Etiam
        gravida lacus sollicitudin nulla mollis cursus. Aliquam dignissim, augue eu rutrum aliquet, nisl neque laoreet
        odio, vel mollis risus leo eu diam.</p>
    </div>
  </div>
</div>

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<!--<h1>Categories#index</h1>-->
<!--<p>Find me in app/views/categories/index.html.erb</p>-->

<div class="categories">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <h2>Categories</h2>
        <p>Explore our latest categories from around the world.</p>
      </div>


      <div class="col-md-8">
        <% @categories.in_groups_of(3).each do |categories| %>
            <% categories.select! {|x| !x.nil?} %>
            <div class='row'>
              <% categories.each do |category| %>
                  <div class='col-md-4'>
                    <div class="thumbnail">
                      <div class="caption">
                        <span class="listing-title"><%= category.name %></span>
                        <span><%= link_to "Edit", edit_category_path(category.id) %></span>
                        <span><%= link_to 'Show', category %></span>
                        <td><%= link_to 'Delete', categories_delete_path(:id => category.id) %></td>
                      </div>
                    </div>
                  </div>
              <% end %>
            </div>
        <% end %>

      </div>



    </div>

  </div>
</div>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/feed/index.html.erb
<!-- feed page -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/feed">lightbulb</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/posts/new"><span class="glyphicon glyphicon-plus"></span> New Project</a></li>
        <li><a href="/posts">Your Projects</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">John Doe <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="/portfolio">
                <span class="glyphicon glyphicon-user"></span>
                <span class="dropdown-text"> Portfolio</span>
              </a>
            </li>
            <li>
              <a href="/applications">
                <span class="glyphicon glyphicon-file"></span>
                <span class="dropdown-text"> Applications</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-star"></span>
                <span class="dropdown-text"> Starred</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-list"></span>
                <span class="dropdown-text"> History</span>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-cog"></span>
                <span class="dropdown-text"> Settings</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-off"></span>
                <span class="dropdown-text"> Logout</span>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</nav>


<div class="container">
  <div class="row">
    <div class="col-md-9">

      <h1 class="page-header">Your Feed</h1>

      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active feed-category">
              <a href="#"><span class="glyphicon glyphicon-th"></span></a>
            </li>
            <% #@categories.each do |category| %>
                <!--<li class="feed-category">
                  <a href="#"><span class="glyphicon glyphicon-<%#= category.name.downcase %>"></span></a>
                </li>-->
            <% #end %>

            <li class="feed-category"><a href="#"><span class="glyphicon glyphicon-film"></span></a></li>
            <li class="feed-category"><a href="#"><span class="glyphicon glyphicon-music"></span></a></li>
            <li class="feed-category"><a href="#"><span class="glyphicon glyphicon-camera"></span></a></li>
            <li class="feed-category"><a href="#"><span class="glyphicon glyphicon-picture"></span></a></li>
            <li class="feed-category"><a href="#"><span class="glyphicon glyphicon-tower"></span></a></li>

          </ul>
        </div>
        <div class="col-sm-9 col-md-10 post-area">

          <div class="post">
            <div class="row">
              <div class="col-md-12">
                <h3>A Rad Music Project</h3>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <img src="http://goo.gl/j78nzh" class="img-rounded post-img">
              </div>
            </div>
            <div class="row">
              <div class="col-md-9">
                <h4>Description</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-default" href="/feed/show" role="button">View details &raquo;</a></p>
              </div>
              <div class="col-md-3">
                <h4>Looking for</h4>
                <ul>
                  <li>Position 1</li>
                  <li>Position 2</li>
                  <li>Position 3</li>
                </ul>
                <!--<p><a class="btn btn-default" href="/apply" role="button">Apply &raquo;</a></p>-->
              </div>
            </div>
          </div>

          <div class="post">
            <div class="row">
              <div class="col-md-12">
                <h3>That Project</h3>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <img src="http://goo.gl/LGbA7M" class="img-rounded post-img">
              </div>
            </div>
            <div class="row">
              <div class="col-md-9">
                <h4>Description</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
              </div>
              <div class="col-md-3">
                <h4>Looking for</h4>
                <ul>
                  <li>Position 1</li>
                  <li>Position 2</li>
                  <li>Position 3</li>
                </ul>
                <p><a class="btn btn-default" href="#" role="button">Apply &raquo;</a></p>
              </div>
            </div>
          </div>

          <div class="post">
            <div class="row">
              <div class="col-md-12">
                <h3>Another Project</h3>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <img src="http://goo.gl/BheHW2" class="img-rounded post-img">
              </div>
            </div>
            <div class="row">
              <div class="col-md-9">
                <h4>Description</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
              </div>
              <div class="col-md-3">
                <h4>Looking for</h4>
                <ul>
                  <li>Position 1</li>
                  <li>Position 2</li>
                  <li>Position 3</li>
                </ul>
                <p><a class="btn btn-default" href="#" role="button">Apply &raquo;</a></p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
    <div class="col-md-3">

      <h1 class="page-header">Filters</h1>

      <form class="form-inline" role="form">
        <div class="form-group">
          <input type="text" placeholder="Keywords" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Search</button>
      </form>

      <br>

      <h4>Search options</h4>
      <h5>Distance </h5>
      <form role="form">
        <div class="checkbox">
          <label><input type="checkbox" name="distance" value="1"> 0 - 1 miles</label>
        </div>
        <div class="checkbox">
          <label><input type="checkbox" name="distance" value="3"> 1 - 3 miles</label>
        </div>
        <div class="checkbox">
          <label><input type="checkbox" name="distance" value="5"> 3 - 5 miles</label>
        </div>
        <div class="checkbox">
          <label><input type="checkbox" name="distance" value="10"> 5 - 10 miles</label>
        </div>
        <div class="checkbox">
          <label><input type="checkbox" name="distance" value="20"> 10 - 20 miles</label>
        </div>
        <div class="checkbox">
          <label><input type="checkbox" name="distance" value="21"> 20+ miles</label>
        </div>
      </form>



    </div>
  </div>
</div>

app/views/feed/show.html.erb
<!-- feed show -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/feed">lightbulb</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/posts/new"><span class="glyphicon glyphicon-plus"></span> New Project</a></li>
        <li><a href="/posts">Your Projects</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">John Doe <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="/portfolio">
                <span class="glyphicon glyphicon-user"></span>
                <span class="dropdown-text"> Portfolio</span>
              </a>
            </li>
            <li>
              <a href="/applications">
                <span class="glyphicon glyphicon-file"></span>
                <span class="dropdown-text"> Applications</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-star"></span>
                <span class="dropdown-text"> Starred</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-list"></span>
                <span class="dropdown-text"> History</span>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-cog"></span>
                <span class="dropdown-text"> Settings</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-off"></span>
                <span class="dropdown-text"> Logout</span>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</nav>



<div class="container">
  <div class="row">

    <div class="col-md-8">
      <h1 class="page-header">A Rad Music Project</h1>
      <div class="post">
        <div class="row">
          <div class="col-md-12">
            <img src="http://goo.gl/j78nzh" class="img-rounded post-img">
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <h4>Description</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultricies eget lectus eu venenatis.
              Phasellus nibh lectus, molestie ut orci quis, feugiat porttitor nunc. Maecenas vitae ipsum et nunc
              sodales finibus et sollicitudin libero. Proin et sem eros. Proin sodales eleifend consequat. Nullam
              egestas enim at laoreet euismod. Duis sit amet purus massa. Sed tristique semper erat et semper. In
              viverra lacus diam, sit amet consectetur mauris convallis in.</p>
          </div>
        </div>

        <hr>

        <div class="row">
          <div class="col-md-12">
            <h4>Roles needed</h4>

            <h5>This Guy</h5>
            <p>Nullam egestas enim at laoreet euismod. Duis sit amet purus massa. Sed tristique semper erat et
              semper. In viverra lacus diam, sit amet consectetur mauris convallis in. Curabitur pharetra at odio
              eu condimentum. </p>
            <p><a class="btn btn-default" href="/apply" role="button">Apply &raquo;</a></p>

            <h5>That Guy</h5>
            <p>Maecenas massa sapien, rutrum ac aliquam blandit, faucibus non dui. Phasellus vitae augue leo.
              Maecenas ornare lacus justo, et aliquet risus fermentum vel. Nullam a nisi auctor, ultricies libero
              eget, finibus felis. </p>
            <p><a class="btn btn-default" href="/apply" role="button">Apply &raquo;</a></p>
          </div>
        </div>

        <br>

      </div>
    </div>



    <div class="col-md-4">
      <h1 class="page-header">Media</h1>
      <div class="row">
        <div class="col-md-12">
          <div class="thumbnail">
            <a href="#">
              <div class="caption">
                <img src="http://goo.gl/0o5QjG" class="img-rounded post-img">
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-12">
          <div class="thumbnail">
            <a href="#">
              <div class="caption">
                <%= image_tag("play.png", :class => "img-rounded post-img") %>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lightbulb</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= yield :head %>
</head>
<body>

<%= yield %>





  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/portfolio/delete.html.erb
<h1>Portfolio#delete</h1>
<p>Find me in app/views/portfolio/delete.html.erb</p>

app/views/portfolio/edit.html.erb
<h1>Portfolio#edit</h1>
<p>Find me in app/views/portfolio/edit.html.erb</p>

app/views/portfolio/index.html.erb
<!-- portfolio -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/feed">lightbulb</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/posts/new"><span class="glyphicon glyphicon-plus"></span> New Project</a></li>
        <li><a href="/posts">Your Projects</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">John Doe <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-user"></span>
                <span class="dropdown-text"> Portfolio</span>
              </a>
            </li>
            <li>
              <a href="/applications">
                <span class="glyphicon glyphicon-file"></span>
                <span class="dropdown-text"> Applications</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-star"></span>
                <span class="dropdown-text"> Starred</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-list"></span>
                <span class="dropdown-text"> History</span>
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-cog"></span>
                <span class="dropdown-text"> Settings</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-off"></span>
                <span class="dropdown-text"> Logout</span>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

<div class="container">
  <div class="row">
    <h1 class="page-header">Your Portfolio</h1>
  </div>
  <div class="row">
  </div>
</div>

app/views/portfolio/new.html.erb
<h1>Portfolio#new</h1>
<p>Find me in app/views/portfolio/new.html.erb</p>

app/views/portfolio/show.html.erb
<h1>Portfolio#show</h1>
<p>Find me in app/views/portfolio/show.html.erb</p>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>